name: Deploy React App to Server

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16 # Use Node.js version compatible with your project

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build the React app
      - name: Build React app
        run: |
          export NODE_OPTIONS="--max-old-space-size=4096"
          npm run build
        env:
          REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}

      # Step 5: Verify the build folder
      - name: Verify build folder
        run: |
          if [ ! -d "build" ]; then
            echo "❌ Build folder not found. Build might have failed."
            exit 1
          fi
          echo "✅ Build folder exists."
          ls -la build
